categories:
- default
conversations:
- - 
  - I can only talk about Biology, please ask me anything related to Biology
  - I don't have an answer for that today, try a different question.
  - I'm not sure what you mean, please explain.